apiVersion: apps/v1
kind: Deployment
metadata:
  name: wtf-posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wtf-posts
  template:
    metadata:
      labels:
        app: wtf-posts
    spec:
      containers:
        - name: posts
          image: ilyazykin/wtf-posts-server:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wtf-api
spec:
  type: NodePort
  selector:
    app: wtf-posts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30548
